# This file is a template, and might need editing before it works on your project.
image: golang:1.11

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/sajfer/surbot

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - test
    - build
    - release
    - deploy

format:
    stage: test
    script:
      - go get -u github.com/bwmarrin/discordgo
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    script:
      - go get -u github.com/bwmarrin/discordgo
      - go build -race -ldflags "-extldflags '-static'" -o surbot
    artifacts:
      paths:
        - surbot

image_build:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - compile
  script:
    - docker info
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
    - docker build -t registry.gitlab.com/${CI_PROJECT_PATH}:latest 
      --build-arg discord_secret=${discord_secret} .
    - echo ${CI_COMMIT_SHA}
    - docker tag registry.gitlab.com/${CI_PROJECT_PATH}:latest registry.gitlab.com/${CI_PROJECT_PATH}:${CI_COMMIT_SHA}
    - test ! -z "${CI_COMMIT_TAG}" && docker push registry.gitlab.com/${CI_PROJECT_PATH}:latest
    - docker push registry.gitlab.com/${CI_PROJECT_PATH}:${CI_COMMIT_SHA}

deploy to production:
  stage: deploy
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: production
  script:
    - kubectl version
    - kubectl delete secret gitlab-registry || true
    - kubectl create secret docker-registry gitlab-registry
      --docker-server="${CI_REGISTRY}"
      --docker-username="${CI_REGISTRY_USER}"
      --docker-password="${CI_REGISTRY_PASSWORD}"
      --docker-email="${GITLAB_USER_EMAIL}"

    - sed -i 's/<TAG>/${CI_COMMIT_SHA}/' deployment/deployment.yml
    - kubectl apply -f deployment/deployment.yml
