apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: surbot-deployment
spec:
  selector:
    matchLabels:
      app: surbot
  replicas: 1
  template:
    metadata:
      labels:
        app: surbot
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: surbot
        image: registry.gitlab.com/v1/sajfer/surbot:<TAG>
        ports:
        - containerPort: 443
        imagePullPolicy: Always