apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "surbot.fullname" . }}-secrets"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DiscordToken: {{ .Values.secrets.discord_token | b64enc }}
  YoutubeApiToken: {{ .Values.secrets.youtube_api | b64enc }}
  SpotifyClientId: {{ .Values.secrets.spotify_clientid | b64enc }}
  SpotifyClientSecret: {{ .Values.secrets.spotify_clientsecret | b64enc }}
