apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ include "surbot.fullname" . }}-secrets"
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: "{{ include "surbot.fullname" . }}-secrets"
    creationPolicy: Owner
  data:
    - secretKey: DiscordToken
      remoteRef:
        key: "kv/surbot/discord"
        property: "token"

    - secretKey: SpotifyClientId
      remoteRef:
        key: "kv/surbot/spotify"
        property: "clientId"

    - secretKey: SpotifyClientSecret
      remoteRef:
        key: "kv/surbot/spotify"
        property: "clientSecret"

    - secretKey: YoutubeApiToken
      remoteRef:
        key: "kv/surbot/youtube"
        property: "token"
