---
name: Checkov
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        env:
          HELM_NAMESPACE: not-default
        with:
          quiet: true
          directory: deployments
          framework: helm
